import localFont from "next/font/local";
import "./globals.css";
import NavSection from "@/components/NavSection";
import HeroSection from "@/components/HeroSection";
import { headers } from "next/headers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "KhanaKhazana || Food",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const headersList = headers();
  const currentUrl = headersList.get("referer") || headersList.get("host");

  const isHomePage = currentUrl?.endsWith("");

  // console.log("URL -------- >>>>>", children); //On Dev

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased md:mx-10 mx-auto`}
      >
        <header>
          <NavSection />
          {isHomePage && <HeroSection />}
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
