import localFont from "next/font/local";
import "./globals.css";

import { dbConnect } from "@/services/mongo";
import AuthProvider from "@/contexts/provider/AuthProvider";
import Header from "@/components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "KhanaKhazana || Food",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await dbConnect(); //Database from MongoDb

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased md:mx-10 mx-auto`}
      >
        <AuthProvider>
          <Header />
          <main>{children}</main>
        </AuthProvider>

        <div id="modal-box"></div>
      </body>
    </html>
  );
}
